apiVersion: apps/v1
kind: Deployment
metadata:
  name: blufountain-business-banking-angular-deployment
  namespace: blufountain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blufountain-business-banking-angular
  template:
    metadata:
      labels:
        app: blufountain-business-banking-angular
    spec:
      containers:
        - name: blufountain-business-banking-angular-container
          image: kaributechsworkflow/blufountain-business-banking-angular:cdf68fa931f158d9770df426009c876c6d077494
          ports:
            - containerPort: 8443
          env:
            - name: PORT
              value: "8443"
